#!/bin/bash

## IMPORTING BASH CONFIG
export BASH_PROFILE_HOME=~/Documents/Work/Workspace/prompt

source "$BASH_PROFILE_HOME"/bash/custom_bash_profile
source "$BASH_PROFILE_HOME"/git/git-completion.bash
source "$BASH_PROFILE_HOME"/git/git-prompt.sh

GIT_PS1_SHOWDIRTYSTATE=true
export LS_OPTIONS='--color=auto'
export CLICOLOR='Yes'
export LSCOLORS=gxfxbEaEBxxEhEhBaDaCaD
stty columns 1000
export PS1=$LIGHT_GRAY"\u@MBP"'$(
    if [[ $(__git_ps1) =~ \*\)$ ]]
    # a file has been modified but not added
    then echo "'$YELLOW'"$(__git_ps1 " (%s)")
    elif [[ $(__git_ps1) =~ \+\)$ ]]
    # a file has been added, but not commited
    then echo "'$MAGENTA'"$(__git_ps1 " (%s)")
    # the state is clean, changes are commited
    else echo "'$CYAN'"$(__git_ps1 " (%s)")
    fi)'$BLUE" \W"$WHITE": "
    